name: Create Project Image

on:
  pull_request:
  push:
    branches:
      - "+([0-9])?(.{+([0-9]),x}).x"
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: .cache/
          key: ${{ hashFiles('package-lock.json') }}
      - run: echo -e ".git\n.cache" > .dockerignore
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - uses: docker/build-push-action@v3
        with:
          file: .github/Dockerfile
          cache-from: type=local,src=.cache
          cache-to: type=local,dest=.cache,mode=max
          target: cache
          push: true
          context: .
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_type == 'tag' && github.ref_name || github.sha }}
            ghcr.io/${{ github.repository }}:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Test
